2025-02-25

diff --git a/tools/smnt b/tools/smnt
--- a/tools/smnt
+++ b/tools/smnt
@@ -6,17 +6,17 @@
 
 dev=$1
 if [ "$dev" == "" ] || [ ! -b $dev ]; then
-	echo -e "\033[97;31misn't block file\033[0m"
-	exit 1
+  echo -e "\033[97;31misn't block file\033[0m"
+  exit 1
 fi
 dir=${dev##*/}
 $prefix mkdir -p "/mnt/$dir"
 $prefix mount $dev /mnt/$dir
 if [ $? -ne 0 ]; then
-	echo -e "\033[0;93;31mmount error:\033[0m"
-	exit 1
+  echo -e "\033[0;93;31mmount error:\033[0m"
+  exit 1
 else
-	echo -e "\033[3;97;32mmount success\033[0m"
+  echo -e "\033[3;97;32mmount success\033[0m"
 fi
 
 
