2024-12-17
調整 shell 腳本格式

diff --git a/tools/smnt b/tools/smnt
--- a/tools/smnt
+++ b/tools/smnt
@@ -1,11 +1,23 @@
-#! /bin/bash
+#!/bin/bash
 
 # 挂载外部磁盘的时候自动在 mnt 目录下创建相应的文件夹
+
+[ $UID -ne 0 ] && prefix=sudo || prefix=""
+
 dev=$1
 if [ "$dev" == "" ] || [ ! -b $dev ]; then
-  echo "必须输入需要挂载的磁盤"
-  return 1
+	echo -e "\033[97;31misn't block file\033[0m"
+	lsblk
+	exit 1
 fi
 dir=${dev##*/}
-sudo mkdir -p "/mnt/$dir"
-sudo mount "$dev" "/mnt/$dir" && lsblk || echo "mount error"
+$prefix mkdir -p "/mnt/$dir"
+$prefix mount $dev /mnt/$dir
+if [ $? -ne 0 ]; then
+	echo -e "\033[0;93;31mmount error:\033[0m"
+	exit 1
+else
+	echo -e "\033[3;97;32mmount success\033[0m"
+fi
+
+
diff --git a/tools/umnt b/tools/umnt
--- a/tools/umnt
+++ b/tools/umnt
@@ -1,6 +1,16 @@
 #! /bin/bash
 
 # 在 umount 时自动删除 smnt 创建的目录
+
+[ $UID -ne 0 ] && prefix=sudo || prefix=""
+
 mounton=$1
-sudo umount $mounton && lsblk || (echo "unmount error" && return 1)
-sudo rmdir $mounton
+$prefix umount $mounton
+if [ $? -ne 0 ];then
+	echo -e "\033[97;31munmount error\033[31m"
+	exit 1
+else
+	echo -e "\033[97;32mumount success\033[0m"
+	lsblk
+	$prefix rmdir $mounton
+fi
