2025-02-27
使用 udisksctl 優化 smnt 和 umnt

diff --git a/tools/smnt b/tools/smnt
--- a/tools/smnt
+++ b/tools/smnt
@@ -2,21 +2,45 @@
 
 # 挂载外部磁盘的时候自动在 mnt 目录下创建相应的文件夹
 
-[ $UID -ne 0 ] && prefix=sudo || prefix=""
+# [ $UID -ne 0 ] && prefix=sudo || prefix=""
+#
+# dev=$1
+# if [ "$dev" == "" ] || [ ! -b $dev ]; then
+#   echo -e "\033[97;31misn't block file\033[0m"
+#   exit 1
+# fi
+# dir=${dev##*/}
+# $prefix mkdir -p "/mnt/$dir"
+# $prefix mount $dev /mnt/$dir
+# if [ $? -ne 0 ]; then
+#   echo -e "\033[0;93;31mmount error:\033[0m"
+#   exit 1
+# else
+#   echo -e "\033[3;97;32mmount success\033[0m"
+# fi
+#
 
-dev=$1
-if [ "$dev" == "" ] || [ ! -b $dev ]; then
-  echo -e "\033[97;31misn't block file\033[0m"
-  exit 1
-fi
-dir=${dev##*/}
-$prefix mkdir -p "/mnt/$dir"
-$prefix mount $dev /mnt/$dir
-if [ $? -ne 0 ]; then
-  echo -e "\033[0;93;31mmount error:\033[0m"
-  exit 1
-else
-  echo -e "\033[3;97;32mmount success\033[0m"
+current_dir=$(dirname $(realpath $0))
+source $current_dir/mod.sh
+
+if [[ -z "$1" ]]; then
+  err "usage: smnt <block-device>"
 fi
 
+if [[ ! -b $1 ]]; then
+  err "$1 not block device"
+fi
+
+mount_dir=$(udisksctl mount -b $1 | awk '{print $NF}')
+if [[ $? -ne 0 ]]; then
+  err "mount error"
+fi
+
+link_dir="$HOME/${mount_dir##*/}"
+if [[ ! -e $link_dir ]]; then
+  ln -sf $mount_dir $HOME/
+  echo "successful mount to: $mount_dir"
+  echo "link to home dir: $link_dir"
+  exit 0
+fi
 
diff --git a/tools/umnt b/tools/umnt
--- a/tools/umnt
+++ b/tools/umnt
@@ -2,15 +2,42 @@
 
 # 在 umount 时自动删除 smnt 创建的目录
 
-[ $UID -ne 0 ] && prefix=sudo || prefix=""
+# [ $UID -ne 0 ] && prefix=sudo || prefix=""
+#
+# mounton=$1
+# $prefix umount $mounton
+# if [ $? -ne 0 ];then
+# 	echo -e "\033[97;31munmount error\033[31m"
+# 	exit 1
+# else
+# 	echo -e "\033[97;32mumount success\033[0m"
+# 	lsblk
+# 	$prefix rmdir $mounton
+# fi
+#
 
-mounton=$1
-$prefix umount $mounton
-if [ $? -ne 0 ];then
-	echo -e "\033[97;31munmount error\033[31m"
-	exit 1
-else
-	echo -e "\033[97;32mumount success\033[0m"
-	lsblk
-	$prefix rmdir $mounton
+current_dir=$(dirname $(realpath $0))
+source $current_dir/mod.sh
+
+if [[ -z "$1" ]]; then
+  err "usage: smnt <block-device>"
+fi
+
+if [[ ! -b $1 ]]; then
+  err "$1 not block device"
+fi
+
+mount_point=$(lsblk -no MOUNTPOINT $1)
+if [[ "$mount_point" == "" ]]; then
+  err "$1 not mount"
+fi
+
+udisksctl unmount -b $1
+if [[ $? -ne 0 ]]; then
+  err "unmout error"
+fi
+
+link_dir="$HOME/${mount_point##*/}"
+if [[ -L $link_dir && ! -e $link_dir ]]; then
+  rm $link_dir
 fi
