2025-08-03
- yazi 選中文件數量角標去除背景色, 確保終端任何主題下都能正常顯示
- 指定 mp3 打開方式爲多媒體文件, 防止部分被識別爲文本文件
- tomp3 腳本允許通過 -r 參數控制是否進行遞歸轉化
- cosb 使用 find 替代 dot_clean 清理文件
- bname 防止同名文件覆蓋
- yazi 修改 y 函數允許通過 $1 直接定位到特定目錄
- mpv 配置格式調整

diff --git a/tools/tomp3 b/tools/tomp3
--- a/tools/tomp3
+++ b/tools/tomp3
@@ -9,27 +9,57 @@ if [[ $(uname -s) != "Darwin" ]]; then
   exit 1
 fi
 
-if ! command -v ffmpeg; then
+if ! command -v ffmpeg > /dev/null 2>&1; then
   echo "not fond ffmpeg command, is required, you can install with brew: brew install ffmpeg"
   exit 1
 fi
 
-for f in *; do
-  m=$(file -b -I "$f" | awk -F'/' '{print $1}')
-  if [[ $m != "audio" ]]; then
-    echo "skip $f, not audio file type ($m)"
-    continue
-  fi
-
-  nn="${f%.*}.mp3"
-  if [[ -f "$nn" ]]; then
-    echo "skip $f, file existed"
-    continue
-  fi
-  ffmpeg -i "$f" -ab 320k "$nn" > /dev/null 2>&1
-  if [[ $? -ne 0 ]]; then
-    echo "convert $f to mp3 error"
-    continue
-  fi
-  echo "convert $f to mp3 successful"
+while getopts "r" opt; do
+  case $opt in
+    r)
+      recursion=1
+      ;;
+    *)
+      echo "unknow flag: $opt"
+      exit 1
+      ;;
+  esac
 done
+
+function conver_to_mp3() {
+  # 優先轉化當前目錄中的音頻文件然後遞歸處理子目錄中的文件
+  for f in "$1"/*; do
+    if [[ ! -f "$f" ]]; then
+      continue
+    fi
+    m=$(file -b -I "$f" | awk -F'/' '{print $1}')
+    if [[ $m != "audio" ]]; then
+      echo "skip $f, not audio file type ($m)"
+      continue
+    fi
+
+    nn="${f%.*}.mp3"
+    if [[ -f "$nn" ]]; then
+      echo "skip $f, file existed"
+      continue
+    fi
+    ffmpeg -i "$f" -ab 320k "$nn" > /dev/null 2>&1
+    if [[ $? -ne 0 ]]; then
+      echo -e "\033[31mfaile      $f\033[0m"
+      continue
+    fi
+    echo "successful $f"
+  done
+
+  # 遞歸處理子目錄
+  if [[ $recursion -ne 0 ]]; then
+    for d in "$1"/*; do
+      if [[ -d "$d" && ! -z $(ls -A "$d") ]]; then
+        echo "$d"
+        conver_to_mp3 "$d"
+      fi
+    done
+  fi
+}
+
+conver_to_mp3 .
